resolver: lts-7.19
packages:
- .
- ../concur-core
extra-deps: []
# - ghcjs-dom-0.9.2.0
# - jsaddle-0.9.4.0
# - jsaddle-warp-0.9.4.0
# - jsaddle-wkwebview-0.9.4.0
# - ghcjs-dom-jsaddle-0.9.2.0
# - ref-tf-0.4.0.1
# - jsaddle-dom-0.9.2.0
flags: {}
extra-package-dbs: []

nix:
  enable: false
